[package]
name = "freyr"
authors = ["Cyprien"]
version = "0.1.2"
edition = "2021"
description = "A UI crate for the Dioxus framework."
license = "MIT"
documentation = "https://docs.rs/freyr/latest/freyr/"
repository = "https://github.com/cbdefontenay/freyr"

[dependencies]
dioxus = { version = "0.5.6", features = ["web", "router"] }
dioxus-logger = "0.5.1"
