[package]
name = "freyr"
authors = ["Cyprien"]
version = "0.1.6"
edition = "2021"
description = "A UI crate for Dioxus web."
license = "MIT"
documentation = "https://docs.rs/freyr/latest/freyr/"
repository = "https://github.com/cbdefontenay/freyr"

[dependencies]
dioxus = { version = "0.6.0-alpha.4", features = ["web", "router"] }
dioxus-logger = "0.5.1"
serde_json = "1.0.133"
